credentials:
  usernames:
    patrickshinzato:
      email: shiguemialexandre@gmail.com
      name: Alexandre Shiguemi Ito
      password: $2b$12$rix95LCFkA1DLowPsA1vHuPXZN5PdwYbN7cGflVR.Ff4XTg7qAQfa
cookie:
  expiry_days: 30
  key: um_segredo_muito_louco_2
  name: big_data_eh_legal
preauthorized:
  emails:
  - shiguemialexandre@gmail.com 
showSidebarNavigation : false